readingDataPointsFilters:
        - RandomSamplingDataPointsFilter:
                prob: 0.15
        - SurfaceNormalDataPointsFilter:
                knn: 20
                epsilon: 3.16 #1 #3.16
                keepNormals: 1
                keepDensities: 0
        - ObservationDirectionDataPointsFilter
        - OrientNormalsDataPointsFilter 
        #- MaxDistDataPointsFilter:
                #maxDist: 35.0
        #- MaxDensityDataPointsFilter:
                #maxDensity: 20.0

#- SimpleSensorNoiseDataPointsFilter:
#sensorType: 0

referenceDataPointsFilters:
        - SurfaceNormalDataPointsFilter:
                knn: 20 #20
                epsilon: 1 #3.16
                keepNormals: 1
                keepDensities: 0
        #- RandomSamplingDataPointsFilter:
                #prob: 0.25
        #- MaxDistDataPointsFilter:
                #maxDist: 35.0
        #- RandomSamplingDataPointsFilter:
                #prob: 0.25
        #- SamplingSurfaceNormalDataPointsFilter:
                #knn: 10
        #- ObservationDirectionDataPointsFilter
        #- OrientNormalsDataPointsFilter 
        #- RandomSamplingDataPointsFilter:
                #prob: 0.15
        #- MaxDensityDataPointsFilter:
                #maxDensity: 20.0
        #- MaxDistDataPointsFilter:
                #maxDist: 35.0
        #- MaxDistDataPointsFilter:
                #maxDist: 100 #35.0

matcher:
        KDTreeMatcher:
                knn: 3 #1 #3 #10 #3 #20 #10 #3
                maxDist: 3 #10 #3 #5 #10.0
                epsilon: 0 #3.33
                #maxDist: 1

#matcher:
        #KDTreeMatcher:
                #knn: 1
                #epsilon: 0

outlierFilters:
        - TrimmedDistOutlierFilter:
                ratio: 0.85 #0.95 #0.9 #0.9
        #- NullOutlierFilter
        #- TrimmedDistOutlierFilter:
                #ratio: 0.95 #0.9 #0.9
        #- MinDistOutlierFilter
        #- SurfaceNormalOutlierFilter:
                #maxAngle: 1 #1.57

errorMinimizer:
        PointToPlaneErrorMinimizer


#PointToPointErrorMinimizer


#PointToPlaneWithCovErrorMinimizer

#PointToPlaneErrorMinimizer

transformationCheckers:
        - CounterTransformationChecker:
                maxIterationCount: 40 #100 #30 #20 #140
        - DifferentialTransformationChecker:
                minDiffRotErr: 0.001
                minDiffTransErr: 0.01
                smoothLength: 4
        #- BoundTransformationChecker:
                #maxRotationNorm: 2.80
                #maxTranslationNorm: 9.00
inspector:
        NullInspector
logger:
        NullLogger

#FileLogger
#NullLogger
