readingDataPointsFilters:
        - RandomSamplingDataPointsFilter:
                prob: 0.15
        - SurfaceNormalDataPointsFilter:
                knn: 20
                epsilon: 3.16
                keepNormals: 1
                keepDensities: 0
        #- MaxDensityDataPointsFilter:
                #maxDensity: 20.0
        - ObservationDirectionDataPointsFilter
        - OrientNormalsDataPointsFilter 

#- SimpleSensorNoiseDataPointsFilter:
#sensorType: 0

referenceDataPointsFilters:
        - RandomSamplingDataPointsFilter:
                prob: 0.15
        - SurfaceNormalDataPointsFilter:
                knn: 20
                epsilon: 3.16
                keepNormals: 1
                keepDensities: 1
        - MaxDensityDataPointsFilter:
                maxDensity: 20.0
        #- ObservationDirectionDataPointsFilter
        #- OrientNormalsDataPointsFilter 
        #- MaxDensityDataPointsFilter:
                #maxDensity: 20.0
        #- SamplingSurfaceNormalDataPointsFilter:
                #knn: 10
        #- MaxDistDataPointsFilter:
                #maxDist: 35.0

matcher:
        KDTreeMatcher:
                knn: 3 #20 #10 #3
                maxDist: 10 #3 #5 #10.0
                epsilon: 3.33

#matcher:
        #KDTreeMatcher:
                #knn: 1
                #epsilon: 0

outlierFilters:
        - TrimmedDistOutlierFilter:
                ratio: 0.85 #0.9 #0.9
        #- SurfaceNormalOutlierFilter:
                #maxAngle: 1 #1.57

errorMinimizer:
        PointToPlaneErrorMinimizer


#PointToPointErrorMinimizer


#PointToPlaneWithCovErrorMinimizer

#PointToPlaneErrorMinimizer

transformationCheckers:
        - CounterTransformationChecker:
                maxIterationCount: 30 #20 #140
        - DifferentialTransformationChecker:
                minDiffRotErr: 0.001
                minDiffTransErr: 0.01
                smoothLength: 4
        #- BoundTransformationChecker:
                #maxRotationNorm: 2.80
                #maxTranslationNorm: 9.00
inspector:
        NullInspector
logger:
        NullLogger
